version: '3.8'

services:
  be-city:
    image: city-be
    container_name: be-city
    ports:
      - '8000:8000'
    networks:
      - citynet

  fe-city:
    image: city-fe
    container_name: fe-city
    ports:
      - '8001:80'
    depends_on:
      - be-city
    networks:
      - citynet

networks:
  citynet:
    driver: bridge
