// This file was auto-generated by prisma-generator-typescript-interfaces

export type UserRole = "USER" | "ADMIN";

export interface Address {
  id: number;
  fullName: string;
  mobile: string;
  addressOne: string;
  adrressTwo: string | null;
  latitude: number;
  longitude: number;
  zip: number | null;
  landmark: string | null;
  country: string;
  state: string;
  city: string | null;
  createdAt: Date;
  updatedAt: Date;
  user?: User | null;
  userId: number | null;
  tenantId: number | null;
  tenant?: Tenant | null;
}

export interface Subscription {
  id: number;
  name: string;
  features: string[];
  isPopular: boolean;
  isActive: boolean;
  cost: number;
  priceSymbol: string;
  costDuration: string;
  createdAt: Date;
  updatedAt: Date;
  Tenant?: Tenant[];
}

export interface Tenant {
  id: number;
  name: string;
  phone: string;
  email: string;
  website: string | null;
  lat: number;
  long: number;
  logo: string | null;
  address?: Address | null;
  userId: number | null;
  user?: User | null;
  createdAt: Date;
  updatedAt: Date;
  subscriptionId: number | null;
  subscription?: Subscription | null;
}

export interface Post {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  title: string;
  content: string | null;
  published: boolean;
  author?: User;
  authorId: number;
}

export interface Profile {
  id: number;
  bio: string | null;
  user?: User;
  userId: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface User {
  id: number;
  email: string;
  name: string | null;
  posts?: Post[];
  profile?: Profile | null;
  role: UserRole;
  password: string | null;
  tokens?: Token[];
  createdAt: Date;
  updatedAt: Date;
  addresses?: Address[];
  tenant?: Tenant | null;
}

export interface Token {
  id: number;
  token: string;
  expirestAt: Date;
  createdAt: Date;
  updatedAt: Date;
  user?: User | null;
  userId: number | null;
}
