export const selectedAddressFields = {
  id: true,
  fullName: true,
  mobile: true,
  addressOne: true,
  adrressTwo: true,
  latitude: true,
  longitude: true,
  zip: true,
  landmark: true,
  country: true,
  state: true,
  city: true,
  userId: true,
};
