apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-city
  namespace: city-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: be-city
  template:
    metadata:
      labels:
        app: be-city
    spec:
      containers:
        - name: be-city
          image: __BE_IMAGE_PATH__
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: be-city
  namespace: city-ns
spec:
  selector:
    app: be-city
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

