apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-frontend
  namespace: city-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-frontend
  template:
    metadata:
      labels:
        app: city-frontend
    spec:
      containers:
        - name: city-frontend
          image: city-fe:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: city-frontend-service
  namespace: city-ns
spec:
  selector:
    app: city-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80    
      nodePort: 30080

