apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-city
  namespace: city-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-city
  template:
    metadata:
      labels:
        app: fe-city
    spec:
      containers:
        - name: fe-city
          image: __FE_IMAGE_PATH__
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fe-city
  namespace: city-ns
spec:
  selector:
    app: fe-city
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80    
      nodePort: 30080

