name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file from secret
        run: |
          mkdir -p apps/backend
          echo "${{ secrets.ENV_FILE }}" > apps/backend/.env

      - name: Build Backend Image
        run: |
          docker build -t city-be -f apps/backend/Dockerfile .

      - name: Build Frontend Image
        run: |
          docker build -t city-fe -f apps/dashboard/Dockerfile .

      - name: Save Backend Image to File
        run: |
          docker save city-be | gzip > city-be.tar.gz

      - name: Save Frontend Image to File
        run: |
          docker save city-fe | gzip > city-fe.tar.gz

      # NEW STEP: Transfer all required files to EC2
      - name: Transfer files to EC2
        uses: appleboy/scp-action@v1.0.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "city-be.tar.gz,city-fe.tar.gz,k8s/*"
          target: "."
          strip_components: 1  # Ensures clean directory structure

      - name: Deploy via SSH on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Load Docker images
            docker load -i city-be.tar.gz
            docker load -i city-fe.tar.gz
            
            # Clean up transferred files
            rm city-be.tar.gz city-fe.tar.gz
            
            # Configure Kubernetes access
            mkdir -p ~/.kube
            sudo cp /etc/kubernetes/admin.conf ~/.kube/config
            sudo chown $(id -u):$(id -g) ~/.kube/config
            
            # Ensure namespace exists
            kubectl create namespace city-ns --dry-run=client -o yaml | kubectl apply -f -
            
            # Apply Kubernetes manifests
            kubectl apply -f k8s/
            
            # Verify deployments
            kubectl rollout status deployment/city-backend -n city-ns --timeout=300s
            kubectl rollout status deployment/city-frontend -n city-ns --timeout=300s
