kname: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file from secret
        run: |
          mkdir -p apps/backend
          echo "${{ secrets.ENV_FILE }}" > apps/backend/.env

      - name: Build Backend Image
        run: |
          docker build -t city-be -f apps/backend/Dockerfile .

      - name: Build Frontend Image
        run: |
          docker build -t city-fe -f apps/dashboard/Dockerfile .

      - name: Save Backend Image to File
        run: |
          docker save city-be | gzip > city-be.tar.gz

      - name: Save Frontend Image to File
        run: |
          docker save city-fe | gzip > city-fe.tar.gz

      # Updated SCP action version
      - name: Transfer files to EC2
        uses: appleboy/scp-action@v0.1.7  # Correct latest stable version
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "city-be.tar.gz,city-fe.tar.gz,k8s/*"
          target: "deployment_files/"
          strip_components: 1

      # Updated SSH action version
      - name: Deploy via SSH on EC2
        uses: appleboy/ssh-action@v1.2.0  # Correct latest stable version
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd deployment_files
            
            # Load Docker images
            docker load -i city-be.tar.gz
            docker load -i city-fe.tar.gz
            
            # Clean up files
            rm city-be.tar.gz city-fe.tar.gz
            
            # Configure Kubernetes
            mkdir -p ~/.kube
            [ -f /etc/kubernetes/admin.conf ] && sudo cp /etc/kubernetes/admin.conf ~/.kube/config
            sudo chown $(id -u):$(id -g) ~/.kube/config
            
            # Create namespace if not exists
            kubectl create namespace city-ns --dry-run=client -o yaml | kubectl apply -f -
            
            # Apply manifests
            kubectl apply -f k8s/
            
            # Verify deployments
            kubectl rollout status deployment/city-backend -n city-ns --timeout=300s
            kubectl rollout status deployment/city-frontend -n city-ns --timeout=300s
