name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file from secret
        run: |
          mkdir -p apps/backend
          echo "${{ secrets.ENV_FILE }}" > apps/backend/.env

      - name: Build Backend Image
        run: |
          docker build -t city-be -f apps/backend/Dockerfile .

      - name: Build Frontend Image
        run: |
          docker build -t city-fe -f apps/dashboard/Dockerfile .

      - name: Save Backend Image to File
        run: |
          docker save city-be | gzip > city-be.tar.gz

      - name: Save Frontend Image to File
        run: |
          docker save city-fe | gzip > city-fe.tar.gz

      - name: Copy Docker Images & Compose File to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            city-be.tar.gz,
            city-fe.tar.gz,
            docker-compose.yml
          target: '/home/${{ secrets.EC2_USER }}/deployment'

      - name: Deploy via SSH on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/deployment
            sudo docker compose down
            sudo docker system prune -af
            sudo docker load < city-be.tar.gz
            sudo docker load < city-fe.tar.gz
            sudo docker compose up -d
